### ISSUE TITLE
how can I see the output

### ISSUE THREAD

**Issue by jianqiao0313** [CoXier/stackoverflow-login#6]
请问   怎么才能看到签到结果啊？
我看了下   /var/lib/docker/containerID/containerID-json.log  里面为空
docker logs containerID   也是为空的

**Comment by CoXier** [comment]
/var/log/login.log 呢

**Comment by jianqiao0313** [comment]
没有这个文件。。。
我用find / -name login.log找到两条
/var/lib/docker/overlay2/fb219b86be4253b2332ab8c811e6e0c3bca07c2a08544f42a54621fe40c24cf1/diff/var/log/login.log
/var/lib/docker/overlay2/fb219b86be4253b2332ab8c811e6e0c3bca07c2a08544f42a54621fe40c24cf1/merged/var/log/login.log
这两条里有记录  谢谢哈
